# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='landownership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='landownership',
            name='num',
        ),
        migrations.RemoveField(
            model_name='landownership',
            name='old_owner',
        ),
        migrations.RemoveField(
            model_name='landownership',
            name='owner',
        ),
        migrations.AlterField(
            model_name='landnum',
            name='owner',
            field=models.ManyToManyField(related_name='land_num', to='account.People', verbose_name='所有人'),
        ),
        migrations.DeleteModel(
            name='LandOwnerShip',
        ),
    ]
