# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='分类名称')),
                ('desc', models.CharField(blank=True, max_length=60, null=True, verbose_name='分类描述')),
                ('create_d', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类名称',
                'verbose_name_plural': '分类名称',
            },
        ),
        migrations.AlterField(
            model_name='moneyaccount',
            name='status',
            field=models.IntegerField(choices=[('-1', '支出'), ('1', '收入')], verbose_name='去向'),
        ),
        migrations.AlterField(
            model_name='moneyaccount',
            name='type',
            field=models.CharField(choices=[('b', '银行'), ('c', '现金')], max_length=1, verbose_name='账目类型'),
        ),
    ]
