# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyaccount',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
