# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20170527_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyaccount',
            name='tag',
            field=models.ManyToManyField(blank=True, to='money.Tag', verbose_name='标签'),
        ),
    ]
