# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20170519_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyaccount',
            name='status',
            field=models.CharField(choices=[('-1', '支出'), ('1', '收入')], max_length=2, verbose_name='去向'),
        ),
    ]
