# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20170520_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyaccount',
            name='tag',
            field=models.ManyToManyField(null=True, to='money.Tag', verbose_name='标签'),
        ),
    ]
