# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20170519_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyaccount',
            name='date',
            field=models.DateField(default=datetime.date(2017, 5, 19), verbose_name='日期'),
        ),
    ]
