# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_auto_20170520_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=120, upload_to='file/money/Y%m%d%/', verbose_name='留档图片')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片说明')),
                ('create_d', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_d', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('money_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.MoneyAccount', verbose_name='对应账款')),
            ],
            options={
                'verbose_name': '流水账留档图片',
                'verbose_name_plural': '流水账留档图片',
                'ordering': ['create_d'],
            },
        ),
    ]
