# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_auto_20170523_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='upload/money/%Y%m%d/thumb', verbose_name='缩略图'),
        ),
    ]
