# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_auto_20170523_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='thumb',
        ),
    ]
