# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170513_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/user.png', upload_to='image/%Y%m%d', verbose_name='头像图片'),
        ),
    ]
