# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livingcost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterrate',
            name='mark_d',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_rate', to='livingcost.CenterWater', verbose_name='抄表日期'),
        ),
    ]
