# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170502_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='发布'),
        ),
    ]
