# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 23:33
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_mardownx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
