# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 23:34
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170601_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='mardownx',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='用英文逗号隔开每个标签', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签'),
        ),
    ]
