# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20170513_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_id',
            field=models.IntegerField(default=1, verbose_name='点赞类型的id'),
            preserve_default=False,
        ),
    ]
